<#--
  @author       Li.hq 
  @contact      lihuiquan@email.szu.edu.cn
  @since         2014/8/7
  @description  网站页面语言配置文件
-->
<#assign 
  Language = {
    "zh": {
      "site-title": "海岸带地理环境监测国家测绘地理信息局重点实验室 & 空间信息智能感知与服务深圳市重点实验室",
      "index": "首页",
      "lab-profile": "实验室概况",
      "lab-intro": "实验室简介",
      "org-struct": "组织构架",
      "lab-equipment": "实验室设备",
      "lab-director": "实验室主任",
      "research-team": "研究团队",
      "teachers": "教师",
      "postdoctoral": "博士后",
      "graduates": "研究生",
      "admin-assistant": "行政助理",
      "research": "科学研究",
      "research-area": "研究方向",
      "research-project": "研究项目",
      "research-findings": "研究成果",
      "research-platform": "成果展示",
      "industrial-application": "产品化应用",
      "exchanges": "学术交流",
      "academic-conference": "学术会议",
      "come-to-visit": "学者来访",
      "visiting": "学者出访",
      "foundation": "开放基金",
      "news": "新闻中心",
      "regulations": "规章制度",
      "achievements": "最新成果",
      "notice": "通知公告",
      "contact": "联系我们",
      "address": "地址：",
      "zip-code": "邮编：",
      "tel": "电话：",
      "email": "邮箱：",
      "any-keywords": "任意关键字",
      "search": "搜索",
      "news-list": "新闻列表",
      "news-notice": "新闻公告",
      "search-result": "搜索结果",
      "international-cooperation": "国际合作",
      "job-vacancies": "人才招聘",
      "committee": "学术委员会",
      "root": "海岸带地理环境监测国家测绘地理信息局重点实验室 | 空间信息智能感知与服务深圳市重点实验室",
      "contact_dpet": "海岸带地理环境监测国家测绘地理信息局重点实<br>验室<br>空间信息智能感知与服务深圳市重点实验室",
      "contact_dpet_2": "海岸带地理环境监测国家测绘地理信息局重点实验室<br>空间信息智能感知与服务深圳市重点实验室",
      "copyright": "&copy;2014 版权所有",
      
      "next-slide": "下一张",
      "prev-slide": "上一张",
      "prev-page": "上一页",
      "next-page": "下一页",
      "pagination-prev": "上一页",
      "pagination-next": "下一页",
      
      "view-all": "查看全部",
      "view": "浏览：",
      "update": "更新：",
      "not-found": "找不到对象",
      "not-found-tips": "抱歉！找不到指定的对象",
      
      "research-direction": "研究方向：",
      "remarks": "备注：",
      "no-record": "暂无记录",
      "all": "全部",
      "researching": "在研",
      "concluding": "结题",
      "number": "序号",
      "project-name": "项目名称",
      "project-type": "项目类别",
      "project-number": "项目编号",
      "execution-time": "执行时间",
      "project-status": "项目情况：",
      "monographs": "专著",
      
      
      "name": "名称",
      "study-content": "内容",
      
      "journal-articles": "期刊论文",
      "conference-articles": "会议论文",
      "thesis": "学位论文",
      "award": "获奖",
      "patent": "专利",
      "authorsname": "完成人",
      
      "title": "标题",
      "date": "日期",
      "username": "姓名",
      "unit": "单位",
      "year": "年度",
      
      "view-details": "查看详细",
      
      "Doctor_of_Philosophy": "博士生",
      "Master": "硕士生",
      "Visiting_Scholar": "特约/访问学者",
      "Graduate": "校友",
      
      "F_Leader": "负&nbsp;责&nbsp;&nbsp;人：",
      "F_Project_Type": "项目类型：",
      "F_Year": "年&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;份：",
      "F_Sources_of_Funding": "经费来源：",
      "F_Research_Period": "研究时间：",
      "F_Contract_Number": "合&nbsp;同&nbsp;&nbsp;号：",
      "F_Abstract": "摘要：",
      "F_to": "至",
      "F_Name": "姓&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;名：",
      "F_Gender": "性&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;别：",
      "F_Title": "职&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;称：",
      "F_Major": "专&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;业：",
      "F_Tel": "电&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;话：",
      "F_Fax": "传&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;真：",
      "F_Research": "研究方向：",
      "F_Term": "任期：",
      "F_Intro": "简介：",
      "F_Journal_Name": "期刊名称：",
      "F_Conference_Name": "会议名称：",
      "F_Conference_Address": "会议地址：",
      "F_All_Authors": "全部作者：",
      "F_Corresponding_Authors": "通信作者：",
      "F_Instructors": "指导老师：",
      "F_Publish_Year": "出版年份：",
      "F_Issue": "卷&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;号：",
      "F_ISSN": "期&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;号：",
      "F_Page": "页&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;码：",
      "F_Department": "单&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;位：",
      "F_Award_Name": "奖励名称： ",
      "F_Award_Category": "奖励类别： ",
      "F_Award_Rating": "奖励等级： ",
      "F_Granting_Units": "授予单位： ",
      "F_Year_Award": "授予年份：",
      "F_Patent_Name": "专利名称：",
      "F_Patent_Category": "专利类别：",
      "F_Type": "类&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;型：",
      "F_Participants": "参加人员：",
      "F_Time": "时&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;间：",
      "F_Address": "地&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;点：",
      "F_Download": "下载：",
      "F_Keywords": "关&nbsp;键&nbsp;&nbsp;字：",
      "F_Fund_Doc_No": "文档编号：",
      "F_Funding_Direction": "资助方向：",
      "F_Whether_Funded": "获得资助：",
      "F_Funding": "资助金额：",
      "F_Data": "数&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;据：",
      "F_Achievements": "成&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;果：",
      "F_View_Papers": "查看全本：",
      "F_Email": "电子邮箱：",
      "F_Dept": "单位：",
      "F_Publisher": "出&nbsp;版&nbsp;&nbsp;社：",
      "F_Publish_Address": "出版地址：",
      "F_ISBN_NO": "ISBN号码：",
      
      "T_Department": "单位",
      "T_Brand": "品牌",
      "T_Serial_NO": "编号",
      "T_Leader": "负责人",
      "T_Model": "型号",
      "T_User_Profile": "的资料",
      "T_User_Introduction": "个人介绍",
      "T_User_Projects": "研究项目",
      "T_User_Work_Experience": "工作简历",
      "T_Search_results_on_the_$keyword": "“$keyword” 的搜索结果",
      "T_Sources_of_Funding": "经费来源",
      "T_Begin_Time": "开始时间",
      "T_End_Time": "结束时间",
      "T_Thesis_Title": "论文名称",
      "T_Journal_Name": "期刊名称",
      "T_Indexed": "收录情况",
      "T_Year_of_Publication": "出版年份",
      "T_Papers_Link": "全文链接",
      "T_Published_Papers": "论文",
      "T_Monographs": "专著",
      "T_Rewarded": "奖励",
      "T_Reward_Name": "奖励名称",
      "T_Granting_Dept": "授予单位",
      "T_Reward_Category": "奖励类别",
      "T_Reward_Rating": "获奖等级",
      "T_Granting_Year": "授予年份",
      "T_Patent_Name": "专利名称",
      "T_Patent_Category": "专利类别",
      "T_Patents": "专利",
      "T_Office": "任职",
      "T_Dept": "工作单位",
      "T_Name": "姓名",
      "T_Title": "职称",
      "T_Major": "专业",
      "T_Time": "时间",
      
      "whereabouts": "工作单位：",
      "graduation_time": "离校时间：",
      
      "M_Click_for_Details": "点击查看详细",
      "M_A_Total_of_$Num_Results": "共有<em>$num</em>个结果",
      "M_No_Picture": "<span class=empty>暂无图片</span>",
      "M_Direction_Sequence": "方向$Sequence：",
      
      "E_Unknow_Error": "抱歉！未知错误，请重试",
      
      "S_Sequence_String": "一 二 三 四 五 六 七 八 九 十 十一 十二 十三 十四",
      "S_Go_Back": "返回列表",
      
      "telno": "(0755)-26979741",
      
      "company-address": "广东省深圳市南山区南海大道3688号<br>深圳大学科技楼1402",
      "company-address2": "广东省深圳市南山区南海大道3688号<br>深圳大学科技楼1402"
    },
    
    "en": {
      "site-title": "Key Laboratory for Geo-Environmental Monitoring of Coastal Zone & Key Laboratory of Spatial Smart Sensing and Services",
      "index": "Home",
      "lab-profile": "Profile",
      "lab-intro": "About us",
      "org-struct": "Org Structure",
      "lab-equipment": "Lab Equipment",
      "lab-director": "Director",
      "research-team": "People",
      "teachers": "Faculties",
      "postdoctoral": "Postdoctors",
      "graduates": "Graduates",
      "admin-assistant": "Administrative Assistant",
      "research": "Researches",
      "research-area": "Directions",
      "research-project": "Projects",
      "research-findings": "Outcomes",
      "research-platform": "Platforms",
      "industrial-application": "Industrial Application",
      "exchanges": "Academic Exchanges",
      "academic-conference": "Academic Conferences",
      "come-to-visit": "Come to visit",
      "visiting": "Visiting",
      "foundation": "Foundation",
      "news": "News & Events",
      "regulations": "Regulations",
      "achievements": "Spotlight",
      "notice": "Notices",
      "contact": "Contact us",
      "address": "Address:",
      "zip-code": "Zip Code:",
      "tel": "Telephone:",
      "email": "Email:",
      "any-keywords": "Any Keywords",
      "search": "Search",
      "news-list": "News List",
      "news-notice": "News & Notices",
      "search-result": "Search Results",
      "job-vacancies": "Vacancies",
      "international-cooperation": "International Cooperations",
      "committee": "Academic Board",
      "root": "Key Laboratory for Geo-Environmental Monitoring of Coastal Zone of the National Administration of Surveying, Mapping and GeoInformation<br>Shenzhen Key Laboratory of Spatial Smart Sensing and Services",
      "contact_dpet": "Key Laboratory for Geo-Environmental<br>Monitoring of Coastal Zone of the National<br>Administration of Surveying, Mapping and<br>GeoInformation<br>Shenzhen Key Laboratory of Spatial Smart<br>Sensing and Services",
      "contact_dpet_2": "Key Laboratory for Geo-Environmental Monitoring of Coastal Zone of the National <br>Administration of Surveying, Mapping and GeoInformation<br>Shenzhen Key Laboratory of Spatial Smart Sensing and Services",
      "copyright": "&copy;2014 All Rights Reserved",
      
      "next-slide": "Next Slide",
      "prev-slide": "Prev Slide",
      "prev-page": "Prev Page",
      "next-page": "Next Page",
      "pagination-prev": "Prev",
      "pagination-next": "Next",
      
      "view-all": "View All",
      "view": "View: ",
      "update": "Update: ",
      
      "research-direction":"Research direction: ",
      "remarks": "Remarks: ",
      "no-record": "No record",
      "not-found": "Object Not Found",
      "not-found-tips": "Sorry! Can not find the specified object.",
      
      "all": "All",
      "researching": "Current",
      "concluding": "Past",
      "number": "NO.",
      "project-name": "Project Name",
      "project-type": "Project Type",
      "project-number": "Project Number",
      "execution-time": "Execution Time",
      "project-status": "Conditions: ",
      "monographs": "Monographs",
      
      "name": "Name",
      "study-content": "Content",
      
      "journal-articles": "Journal Papers",
      "conference-articles": "Conference Papers",
      "thesis": "Theses",
      "award": "Award",
      "patent": "Patent",
      "authorsname": "Authors",
      
      "title": "Title",
      "date": "Date",
      "username": "Name",
      "unit": "Unit",
      "year": "Year",
      
      "view-details": "View Details",
      
      "Doctor_of_Philosophy": "PhD Students",
      "Master": "Master Students",
      "Visiting_Scholar": "Visiting Scholars",
      "Graduate": "Alumni",
      
      "F_Leader": "Leader: ",
      "F_Project_Type": "Project Type: ",
      "F_Year": "Year: ",
      "F_Sources_of_Funding": "Sources of Funding: ",
      "F_Research_Period": "Research Period: ",
      "F_Contract_Number": "Contract Number: ",
      "F_Abstract": "Abstract: ",
      "F_to": "to",
      "F_Name": "Name: ",
      "F_Gender": "Gender: ",
      "F_Title": "Position: ",
      "F_Major": "Major: ",
      "F_Tel": "Tel: ",
      "F_Fax": "Fax: ",
      "F_Research": "Research Direction: ",
      "F_Term": "Term: ",
      "F_Intro": "Intro: ",
      "F_Journal_Name": "Journal Name: ",
      "F_Conference_Name": "Conference Name: ",
      "F_Conference_Address": "Conference Address: ",
      "F_All_Authors": "Authors: ",
      "F_Corresponding_Authors": "Corresponding Authors: ",
      "F_All_Authors": "Authors: ",
      "F_Instructors": "Instructors: ",
      "F_Publish_Year": "Publish Year: ",
      "F_Issue": "Issue: ",
      "F_ISSN": "ISSN: ",
      "F_Page": "Page: ",
      "F_Dept": "Dept: ",
      "F_Award_Name": "Award Name: ",
      "F_Award_Category": "Award Category: ",
      "F_Award_Rating": "Award Rating: ",
      "F_Granting_Units": "Granting Units: ",
      "F_Year_Award": "Year Award: ",
      "F_Patent_Name": "Patent Name: ",
      "F_Patent_Category": "Patent Category: ",
      "F_Type": "Type: ",
      "F_Participants": "Participants: ",
      "F_Time": "Time: ",
      "F_Address": "Address: ",
      "F_Download": "Download: ",
      "F_Keywords": "Keywords: ",
      "F_Fund_Doc_No": "Fund Doc No: ",
      "F_Funding_Direction": "Funding Direction: ",
      "F_Whether_Funded": "Whether Funded: ",
      "F_Funding": "Funding: ",
      "F_Data": "Data: ",
      "F_Achievements": "Achievements: ",
      "F_View_Papers": "View Papers: ",
      "F_Email": "Email: ",
      "F_Department": "Department: ",
      "F_Publisher": "Publisher: ",
      "F_Publish_Address": "Publish Address: ",
      "F_ISBN_NO": "ISBN: ",
      
      "T_Department": "Dept",
      "T_Brand": "Brand",
      "T_Serial_NO": "Serial NO.",
      "T_Leader": "Leader",
      "T_Model": "Model",
      "T_User_Profile": "'s Profile",
      "T_User_Introduction": "Resume",
      "T_User_Projects": "Projects",
      "T_User_Work_Experience": "Work Experience",
      "T_Search_results_on_the_$keyword": "Search results on the '$keyword'",
      "T_Sources_of_Funding": "Funding Sources",
      "T_Begin_Time": "Begin Time",
      "T_End_Time": "End Time",
      "T_Thesis_Title": "Thesis Title",
      "T_Journal_Name": "Journal Name",
      "T_Indexed": "Indexed",
      "T_Year_of_Publication": "Year of Publication",
      "T_Papers_Link": "Papers Link",
      "T_Published_Papers": "Publications",
      "T_Monographs": "Monographs",
      "T_Rewarded": "Rewarded",
      "T_Reward_Name": "Reward Name",
      "T_Granting_Dept": "Granting Dept",
      "T_Reward_Category": "Reward Category",
      "T_Reward_Rating": "Reward Rating",
      "T_Granting_Year": "Granting Year",
      "T_Patent_Name": "Patent Name",
      "T_Patent_Category": "Patent Category",
      "T_Patents": "Patents",
      "T_Office": "Office",
      "T_Dept": "Dept",
      "T_Name": "Name",
      "T_Title": "Title",
      "T_Major": "Major",
      "T_Time": "Time",
      
      "whereabouts": "Employer:",
      "graduation_time": "Leaving date:",
      
      "M_Click_for_Details": "Click here for details",
      "M_A_Total_of_$Num_Results": "A total of <em>$num</em> results",
      "M_No_Picture": "<span class=empty>No picture</span>",
      "M_Direction_Sequence": "Direction $Sequence: ",
      
      "E_Unknow_Error": "Sorry! Unknown error, please try again",
      
      "S_Sequence_String": "I II III IV V VI VII VIII IX X",
      "S_Go_Back": "Back to List",
      
      "telno": "+0086 (0)755 26979741",
      
      "company-address": "Room 1402, Science and Technology<br>Building, Shenzhen University <br>No. 3688 Nanhai Avenue, Nanshan District,<br>Shenzhen, Guangdong, P.R.China",
      "company-address2": "Room 1402, Science and Technology Building, Shenzhen University <br>No. 3688 Nanhai Avenue, Nanshan District, Shenzhen, Guangdong, P.R.China"
    }
  }
  
>

<#--
  set global locale && L
-->
<#assign locale = ["zh", "en"][(language!"0")?number]>
<#assign L = Language[locale]>

<#macro language_script>
  <script type="text/javascript">
    <#assign keys = L?keys>
    var lang = {
      <#list keys as key>
        <#if (key_index == 0)>
          "${key}": "${L[key]}"
        <#else>
          ,"${key}": "${L[key]}"
        </#if>
      </#list>
    };
    
  </script>
</#macro>

